### ISSUE TITLE
Premier rendu

### ISSUE THREAD

**Issue by ThomasMonneret** [PolytechLyon/2019-isi3-graph-marguet_monneret#1]

**Comment by Slashgear** [comment]
- 👍 pour le rapport

- Seriez vous m'expliquer la différence entre un `Set` et une `List` en Java ?
https://github.com/PolytechLyon/2019-isi3-graph-marguet_monneret/blob/9c23d214d52ad83c10eeac859221dfaeb5ccfc41/src/main/java/graph/Graph.java#L42-L44

- Pour l'itérateur c'est pas mal 👍 

- Pourquoi conserver des paramètres préfixés par `_` à quelques endroits uniquement ?

- Pourquoi ici nous devrions passer par un Attribut de type IDirectedGraph ?

https://github.com/PolytechLyon/2019-isi3-graph-marguet_monneret/blob/9c23d214d52ad83c10eeac859221dfaeb5ccfc41/src/main/java/graph/UndirectedGraph.java#L8

**Comment by HugoMarguet** [comment]
En java, une `List` est une séquence ordonnée d'éléments qui ont chacun une position dans la liste. On peut d’ailleurs accéder à un élément via son index. Un `set` a la particularité de ne contenir aucun doublon et il n'existe pas d'ordonnement des éléments.

On a gardé les paramètres préfixés par `_ `seulement pour les méthodes faisant apparaître des attributs de la classe afin de ne pas confondre attributs et paramètres.

Nous devrions passer par un attribut de type IDirectedGraph car le graphe non-orienté est un cas particulier du graphe orienté, il est donc plus cohérent de composer avec IDerectedGraph.
